export default {
    // 页面数据初始化
    STAT_FETCH_BLOG_DATA:'STAT_FETCH_BLOG_DATA',
    FETCH_BLOG_DATA_SUCCESS:'FETCH_BLOG_DATA_SUCCESS',
    FETCH_BLOG_DATA_FAILED:'FETCH_BLOG_DATA_FAILED',

    // 记忆训练数据初始化
    STAT_FETCH_MEMORY_DATA:'STAT_FETCH_MEMORY_DATA',
    FETCH_MEMORY_DATA_SUCCESS:'FETCH_MEMORY_DATA_SUCCESS',
    FETCH_MEMORY_DATA_FAILED:'FETCH_MEMORY_DATA_FAILED',
}